

service: serverless-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2


package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
<<<<<<< HEAD
  graphqlServer:
=======
  hello:
>>>>>>> aa51866445a23fd8d6f8a8050bb8133413b9eb97
    handler: bin/graphqlServer
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true


